[package]
name = "northlands"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
rand = "0.8.5"

# Enable max optimizations for dependencies, but not for our code.
# See https://bevy-cheatbook.github.io/pitfalls/performance.html
[profile.dev.package."*"]
opt-level = 3